# Generated by Django 5.2.6 on 2025-10-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_producto_taller'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_completa', models.TextField(verbose_name='Descripción, objetivos y materiales')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='talleres/')),
                ('fecha_proxima', models.DateField(verbose_name='Fecha del Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('lugar', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('profesor', models.CharField(default='Carolina López Pérez', max_length=100)),
                ('capacidad', models.IntegerField(default=8, verbose_name='Capacidad Máxima')),
                ('tipo_taller', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online')], default='PRESENCIAL', max_length=20)),
                ('taller_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Web.taller', verbose_name='Tipo de Taller')),
            ],
            options={
                'verbose_name': 'Taller Programado',
                'verbose_name_plural': 'Talleres Programados',
            },
        ),
    ]
