# Generated by Django 5.2.6 on 2025-10-22 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_tallerevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
