# Generated by Django 5.2.6 on 2025-10-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_carritoitem_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='taller_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.tallerevento'),
        ),
    ]
