# Generated by Django 5.2.7 on 2025-11-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_orden_ordenitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
