# Generated by Django 5.2.7 on 2025-11-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_ordenitem_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='talleres/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='tienda.tallerevento')),
            ],
        ),
    ]
