# Generated by Django 5.2.7 on 2025-11-23 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_imagentaller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('porcentaje_descuento', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('uso_unico', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('aplica', models.CharField(choices=[('ALL', 'Todos'), ('PRODUCTO', 'Productos'), ('TALLER', 'Talleres')], default='ALL', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Si vacío -> cupón público/global. Si tiene usuarios -> cupón asignado.', related_name='cupones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CuponAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tienda.cupon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cupon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cupon', 'usuario')},
            },
        ),
    ]
