# Generated by Django 5.2.7 on 2025-11-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_cupon_cuponasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cupon_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
