# Generated by Django 5.2.7 on 2025-11-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_orden_cupon_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='email_beneficiario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='es_regalo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='nombre_beneficiario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='email_beneficiario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='es_regalo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='nombre_beneficiario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
