# Generated by Django 5.2.6 on 2025-10-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('asunto', models.CharField(choices=[('cotizacion', 'Cotización de taller para empresa'), ('dudas', 'Dudas generales'), ('problemas', 'Problemas con mi reserva'), ('otros', 'Otros')], max_length=50)),
                ('mensaje', models.TextField()),
                ('suscripcion', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
