# Generated by Django 5.2.7 on 2025-11-13 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_resena'),
        ('tienda', '0007_imagentaller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='taller',
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='resena',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Resena_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tallerevento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
            },
        ),
    ]
